initial commit
chorus12/mlops pull request #1
Opened 2021-08-20 08:56 UTC by plaguedoctor39

2021-08-20 09:16 UTC, chorus12 commented
доработай, пожалуйста, с учетом замечаний

2021-08-20 09:17 UTC, chorus12 requested changes
change as discussed

2021-08-23 09:41 UTC, plaguedoctor39 commented
Мне делать merge?

2021-08-24 08:19 UTC, chorus12 approved these changes
good change - let's go further

2021-08-24 08:19 UTC, merged